from django.conf import settings
import pytest


API_KEY = (
    "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9."
    "eyJzdWIiOjcxMjA1OTk3OTA5NzI4NDcwOTQsImV4cCI6MTcyMDc4NjQwN30."
    "-xGFp4GJTtHZnxo0iGngeRnL04uT-mbKmmPNv95EoYdu8aLVvaHhDq2xdamCQ45KYe_x6A4yr4yB4YI9TmO_Cw"
)

SIGNING_KEYS = [
    {
        "kty": "OKP",
        "alg": "EdDSA",
        "crv": "Ed25519",
        "x": "URvrWoqvlzw9F1DU_De_uRZmWR-OzusYsJGp4CLvaDo",
    }
]

def pytest_configure():
    # Just the public part of a key,
    # generated by openssl, as described in readme.
    keys = SIGNING_KEYS
    settings.configure(APIKEY_LOCALKEYS=keys, APIKEY_MANDATORY=False)  #  APIKEY_LOGGER=None)


@pytest.fixture
def signing_keys():
    return SIGNING_KEYS
