from django.conf import settings
import pytest


API_KEY = (
    # Generated in the admin, valid until 2999
    "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9."
    "eyJzdWIiOiI4NDcwMDg1Mjk0Mjk0MTg5NjEzIiwiZXhwIjozMjUwMzY0MzI4M30."
    "jei5bnTEt0AgebJEaR8ITYx9Pme8mS5_jieerH1T671FZnM5vGeGEzGoAGl-YPpqPur4fyMwhw0ergz6sEAgDA"
)

SIGNING_KEYS = [
    {
        "kty": "OKP",
        "alg": "EdDSA",
        "crv": "Ed25519",
        "x": "nZ3GKPXb5dYcDbBVooqAF-iWM65AlWFTcH9FePU9_LQ",
    }
]


def pytest_configure():
    # Just the public part of a key,
    # generated by openssl, as described in readme.
    keys = SIGNING_KEYS
    settings.configure(
        APIKEY_LOCALKEYS=keys, APIKEY_MANDATORY=False, APIKEY_ALLOW_EMPTY=False
    )  #  APIKEY_LOGGER=None)


@pytest.fixture
def signing_keys():
    return SIGNING_KEYS
