from django.conf import settings


def pytest_configure():
    # Just the public part of a key,
    # generated by openssl, as described in readme.
    keys = [
        {
            "kty": "OKP",
            "alg": "EdDSA",
            "crv": "Ed25519",
            "x": "URvrWoqvlzw9F1DU_De_uRZmWR-OzusYsJGp4CLvaDo",
        }
    ]
    settings.configure(APIKEY_LOCALKEYS=keys, APIKEY_MANDATORY=False)  #  APIKEY_LOGGER=None)
