# Services for local development
version: "3.3"
services:
  web:
    build: server
    ports:
      - "8001:8000"
    environment:
      DATABASE_HOST: "database"
      UWSGI_HTTP_SOCKET: ":8000"
      UWSGI_MODULE: "apikeyserv.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/apikeyserv/static=/static"
      UWSGI_PY_AUTORELOAD: 1
    volumes:
      - ./server:/app
    links:
      - database
  database:
    image: amsterdam/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "insecure"
    volumes:
      - ./init-db-user.sh:/docker-entrypoint-initdb.d/init-db-user.sh
