# Services for local development
version: "3.3"
services:
  web:
    build: server
    ports:
      - "8001:8000"
    environment:
      DATABASE_HOST: "database"
      UWSGI_HTTP_SOCKET: ":8000"
      UWSGI_MODULE: "apikeyserv.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/apikeyserv/static=/static"
      UWSGI_PY_AUTORELOAD: 1
    volumes:
      - ./server:/app
    links:
      - database
  client:
    build: client
    ports:
      - "8002:8000"
      - "4444:4444"
    environment:
      APIKEY_ENDPOINT: "http://web:8000/signingkeys"
      APIKEY_MANDATORY: 0
      REMOTE_PDB_HOST: 127.0.0.1 
      REMOTE_PDB_PORT: 4444 
    # command: ["sleep", "infinity"]
  database:
    image: postgres:12.15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "insecure"
    volumes:
      - ./init-db-user.sh:/docker-entrypoint-initdb.d/init-db-user.sh
