# Services for local development
version: "3.3"
services:
  web:
    build: src
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "database"
      UWSGI_HTTP_SOCKET: ":8000"
      UWSGI_MODULE: "apikeyserv.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/apikeyserv/static=/static"
      UWSGI_PY_AUTORELOAD: 1
    volumes:
      - ./src:/app
    links:
      - database
  database:
    image: amsterdam/postgres
    environment:
      POSTGRES_PASSWORD: "insecure"
    volumes:
      - ./init-db-user.sh:/docker-entrypoint-initdb.d/init-db-user.sh