[pytest]
DJANGO_SETTINGS_MODULE = apikeyserv.settings
addopts = --cov=apikeys --cov=apikeyserv --cov-config=../.coveragerc --cov-report=term-missing --cov-report=xml:coverage-server.xml --cov-fail-under=49
