# Generated by Django 3.2.18 on 2023-05-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='name',
            new_name='organisation',
        ),
        migrations.AddField(
            model_name='apikey',
            name='reason',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='apikey',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
