# Generated by Django 5.2.17 on 2026-09-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0003_remove_apikey_email_remove_apikey_reason_and_more_squashed_0005_alter_apikey_email_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='signingkey',
            name='algorithm',
            field=models.CharField(choices=[('EdDSA', 'EdDSA (Ed25519)'), ('ML-DSA-65', 'ML-DSA-65 (post-quantum, FIPS 204)')], default='EdDSA', max_length=32),
        ),
    ]
