[build-system]
requires = ["setuptools", "wheel"]

[tool.isort]
profile = "black"
line_length = 99

[tool.black]
line-length = 99
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''

github_url = "https://github.com/Amsterdam/apikeyserv"
